src/Presentation/Soft.Web/Administration/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Principal;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Soft.Admin.Extensions;
using Soft.Admin.Models.Common;
using Soft.Core;
using Soft.Core.Caching;
using Soft.Core.Domain.Catalog;
using Soft.Core.Domain.Directory;
using Soft.Core.Plugins;
using Soft.Services.Common;
using Soft.Services.Customers;
using Soft.Services.Directory;
using Soft.Services.Helpers;
using Soft.Services.Localization;
using Soft.Services.Orders;
using Soft.Services.Payments;
using Soft.Services.Security;
using Soft.Services.Seo;
using Soft.Services.Shipping;
using Soft.Services.Stores;
using Soft.Web.Framework.Kendoui;
using Soft.Web.Framework.Security;

namespace Soft.Admin.Controllers
{
    public class CommonController : BaseAdminController
    {
        #region Ctor

        public CommonController(IPaymentService paymentService,
            IShippingService shippingService,
            IShoppingCartService shoppingCartService,
            ICurrencyService currencyService,
            IMeasureService measureService,
            ICustomerService customerService,
            IUrlRecordService urlRecordService,
            IWebHelper webHelper,
            CurrencySettings currencySettings,
            MeasureSettings measureSettings,
            IDateTimeHelper dateTimeHelper,
            ILanguageService languageService,
            IWorkContext workContext,
            IStoreContext storeContext,
            IPermissionService permissionService,
            ILocalizationService localizationService,
            ISearchTermService searchTermService,
            IStoreService storeService,
            CatalogSettings catalogSettings,
            HttpContextBase httpContext)
        {
            _paymentService = paymentService;
            _shippingService = shippingService;
            _shoppingCartService = shoppingCartService;
            _currencyService = currencyService;
            _measureService = measureService;
            _customerService = customerService;
            _urlRecordService = urlRecordService;
            _webHelper = webHelper;
            _currencySettings = currencySettings;
            _measureSettings = measureSettings;
            _dateTimeHelper = dateTimeHelper;
            _languageService = languageService;
            _workContext = workContext;
            _storeContext = storeContext;
            _permissionService = permissionService;
            _localizationService = localizationService;
            _searchTermService = searchTermService;
            _storeService = storeService;
            _catalogSettings = catalogSettings;
            _httpContext = httpContext;
        }

        #endregion

        #region Metodos

        public ActionResult SystemInfo()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageMaintenance))
                return AccessDeniedView();

            var model = new SystemInfoModel();
            model.SoftVersion = SoftVersion.CurrentVersion;
            try
            {
                model.OperatingSystem = Environment.OSVersion.VersionString;
            }
            catch (Exception)
            {
            }
            try
            {
                model.AspNetInfo = RuntimeEnvironment.GetSystemVersion();
            }
            catch (Exception)
            {
            }
            try
            {
                model.IsFullTrust = AppDomain.CurrentDomain.IsFullyTrusted.ToString();
            }
            catch (Exception)
            {
            }

            model.ServerTimeZone = TimeZone.CurrentTimeZone.StandardName;
            model.ServerLocalTime = DateTime.Now;
            model.UtcTime = DateTime.UtcNow;
            model.HttpHost = _webHelper.ServerVariables("HTTP_HOST");
            foreach (var key in _httpContext.Request.ServerVariables.AllKeys)
            {
                model.ServerVariables.Add(new SystemInfoModel.ServerVariableModel
                {
                    Name = key,
                    Value = _httpContext.Request.ServerVariables[key]
                });
            }
            //Environment.GetEnvironmentVariable("USERNAME");
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                model.LoadedAssemblies.Add(new SystemInfoModel.LoadedAssembly
                {
                    FullName = assembly.FullName
                    //we cannot use Location property in medium trust
                    //Location = assembly.Location
                });
            }
            return View(model);
        }

        public ActionResult Warnings()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageMaintenance))
                return AccessDeniedView();

            var model = new List<SystemWarningModel>();

            //store URL
            var currentStoreUrl = _storeContext.CurrentStore.Url;
            if (!String.IsNullOrEmpty(currentStoreUrl) &&
                (currentStoreUrl.Equals(_webHelper.GetStoreLocation(false), StringComparison.InvariantCultureIgnoreCase)
                 ||
                 currentStoreUrl.Equals(_webHelper.GetStoreLocation(true), StringComparison.InvariantCultureIgnoreCase)
                    ))
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.URL.Match")
                });
            else
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Warning,
                    Text =
                        string.Format(_localizationService.GetResource("Admin.System.Warnings.URL.NoMatch"),
                            currentStoreUrl, _webHelper.GetStoreLocation(false))
                });


            //primary exchange rate currency
            var perCurrency = _currencyService.GetCurrencyById(_currencySettings.PrimaryExchangeRateCurrencyId);
            if (perCurrency != null)
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.Set")
                });
                if (perCurrency.Rate != 1)
                {
                    model.Add(new SystemWarningModel
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.Rate1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.NotSet")
                });
            }

            //primary store currency
            var pscCurrency = _currencyService.GetCurrencyById(_currencySettings.PrimaryStoreCurrencyId);
            if (pscCurrency != null)
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.PrimaryCurrency.Set")
                });
            }
            else
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.PrimaryCurrency.NotSet")
                });
            }


            //base measure weight
            var bWeight = _measureService.GetMeasureWeightById(_measureSettings.BaseWeightId);
            if (bWeight != null)
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.Set")
                });

                if (bWeight.Ratio != 1)
                {
                    model.Add(new SystemWarningModel
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.Ratio1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.NotSet")
                });
            }


            //base dimension weight
            var bDimension = _measureService.GetMeasureDimensionById(_measureSettings.BaseDimensionId);
            if (bDimension != null)
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultDimension.Set")
                });

                if (bDimension.Ratio != 1)
                {
                    model.Add(new SystemWarningModel
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.DefaultDimension.Ratio1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel
                {
                    Level = SystemWarningLevel.Fail,

src/Presentation/Soft.Web/Administration/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Soft.Admin.Controllers
{
    public class CustomerController : BaseAdminController
    {
    }
}

src/Presentation/Soft.Web/Administration/Views/Shared/Delete.cshtml
@model Soft.Web.Framework.Mvc.DeleteConfirmationModel
@using (Html.BeginForm(Model.ActionName, Model.ControllerName, new { id = Model.Id }))
{
    <div>
        <p>
            @T("Admin.Common.DeleteConfirmation")
        </p>
        <div class="form-actions">
            <span id="" class="k-button" onclick="$('#@Model.WindowId').data('kendoWindow').close();">@T("Admin.Common.NoCancel")</span>
            <input type="submit" class="k-button" value="@T("Admin.Common.Delete")" />
        </div>
    </div>
}

src/Presentation/Soft.Web/Administration/Views/Shared/Menu.cshtml
@using Soft.Web.Framework.Menu;
@{
    //load sitemap
    var siteMap = new  XmlSiteMap();
    siteMap.LoadFrom("~/Administration/sitemap.config");

    //menu plugin
    var adminMenuPlugins = EngineContext.Current.Resolve<Soft.Core.Plugins.IPluginFinder>()
        .GetPlugins<IAdminMenuPlugin>()
        .Where(x => x.Authenticate())
        .ToList();
}
@helper RenderMenuItem(Soft.Web.Framework.Menu.SiteMapNode item)
{
    string url = null;
    if (!string.IsNullOrEmpty(item.ControllerName) && !string.IsNullOrEmpty(item.ActionName))
    {
        url = Url.Action(item.ActionName, item.ControllerName, item.RouteValues, null, null);
    }
    else if (!string.IsNullOrEmpty(item.Url))
    {
        url = item.Url.StartsWith("~/", StringComparison.Ordinal) ? Url.Content(item.Url) : item.Url;
    }
    <li>

        @if (!String.IsNullOrEmpty(url))
        {
            <a href="@url">
                @if (!String.IsNullOrEmpty(item.ImageUrl))
                {
                    <text>
                        <img alt="" src="@Url.Content(item.ImageUrl)" />
                    </text>
                }
                @item.Title
            </a>
        }
        else
        {
            if (!String.IsNullOrEmpty(item.ImageUrl))
            {
                <text>
                    <img alt="" src="@Url.Content(item.ImageUrl)" />
                </text>
            }
            @item.Title
        }
        @if (item.ChildNodes.Any(x => x.Visible))
        {
            <ul>
                @foreach (var childItem in item.ChildNodes.Where(x => x.Visible))
                {
                    @RenderMenuItem(childItem)
                }
            </ul>
        }
    </li>
}

<ul id="admin-menu">
    @foreach (var item in siteMap.RootNode.ChildNodes.Where(x => x.Visible))
    {
        @RenderMenuItem(item)
    }
    @*plugin custom items*@
    @if (adminMenuPlugins.Any())
    {
        var pluginRootMenuItem = new Soft.Web.Framework.Menu.SiteMapNode
        {
            Title = T("Admin.Plugins").Text,
            Visible = true
        };
        foreach (var adminMenuPlugin in adminMenuPlugins)
        {
            pluginRootMenuItem.ChildNodes.Add(adminMenuPlugin.BuildMenuItem());
        }
        @RenderMenuItem(pluginRootMenuItem)
    }
</ul>
<script>
    $(document).ready(function() {
        $("#admin-menu").kendoMenu();
    });
</script>

src/Presentation/Soft.Web/Administration/Views/Shared/Notifications.cshtml
@{
    //success messages
    var successMessages = new List<string>();
    if (TempData[string.Format("soft.notifications.{0}", NotifyType.Success)] != null)
    {
        successMessages.AddRange(TempData[string.Format("soft.notifications.{0}", NotifyType.Success)] as IList<string>);
    }
    if (ViewData[string.Format("soft.notifications.{0}", NotifyType.Success)] != null)
    {
        successMessages.AddRange(ViewData[string.Format("soft.notifications.{0}", NotifyType.Success)] as IList<string>);
    }


    //error messages
    var errorMessages = new List<string>();
    if (TempData[string.Format("soft.notifications.{0}", NotifyType.Error)] != null)
    {
        errorMessages.AddRange(TempData[string.Format("soft.notifications.{0}", NotifyType.Error)] as IList<string>);
    }
    if (ViewData[string.Format("soft.notifications.{0}", NotifyType.Error)] != null)
    {
        errorMessages.AddRange(ViewData[string.Format("soft.notifications.{0}", NotifyType.Error)] as IList<string>);
    }
}
@foreach (var message in successMessages)
{
    <div class="messageBox messageBoxSuccess">
        @message
    </div>
}
@foreach (var message in errorMessages)
{
    <div class="messageBox messageBoxError">
        @message
    </div>
}

src/Presentation/Soft.Web/Administration/Views/Shared/_AddressAttributes.cshtml
@model IList<AddressModel.AddressAttributeModel>
@using Soft.Core.Domain.Catalog;
@foreach (var attribute in Model)
{
    string controlId = string.Format("address_attribute_{0}", attribute.Id);
    string textPrompt = attribute.Name;

    <tr>
        <td class="adminTitle">
            @textPrompt:
        </td>
        <td class="adminData">

            @switch (attribute.AttributeControlType)
            {
                case AttributeControlType.DropdownList:
                    {
                        <select name="@(controlId)" id="@(controlId)">
                            @if (!attribute.IsRequired)
                            {
                                <option value="0">---</option>
                            }
                            @foreach (var attributeValue in attribute.Values)
                            {
                                <option selected="@attributeValue.IsPreSelected" value="@attributeValue.Id">@attributeValue.Name</option>
                            }
                        </select>
                    }
                    break;
                case AttributeControlType.RadioList:
                    {
                        <ul class="option-list">
                            @foreach (var attributeValue in attribute.Values)
                            {
                                <li>
                                    <input id="@(controlId)_@(attributeValue.Id)" type="radio" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" />
                                    <label for="@(controlId)_@(attributeValue.Id)">@attributeValue.Name</label>
                                </li>
                            }
                        </ul>
                    }
                    break;
                case AttributeControlType.Checkboxes:
                case AttributeControlType.ReadonlyCheckboxes:
                    {
                        <ul class="option-list">
                            @foreach (var attributeValue in attribute.Values)
                            {
                                <li>
                                    <input id="@(controlId)_@(attributeValue.Id)" type="checkbox" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" @(attribute.AttributeControlType == AttributeControlType.ReadonlyCheckboxes ? Html.Raw(" disabled=\"disabled\"") : null) />
                                    <label for="@(controlId)_@(attributeValue.Id)">@attributeValue.Name</label>
                                </li>
                            }
                        </ul>
                    }
                    break;
                case AttributeControlType.TextBox:
                    {
                        <input name="@(controlId)" type="text" class="text-box single-line" id="@(controlId)" value="@attribute.DefaultValue" />
                    }
                    break;
                case AttributeControlType.MultilineTextbox:
                    {
                        <textarea id="@(controlId)" style="Width: 250px; Height: 150px;" name="@(controlId)">@attribute.DefaultValue</textarea>
                    }
                    break;
                case AttributeControlType.Datepicker:
                case AttributeControlType.FileUpload:
                case AttributeControlType.ColorSquares:
                    {
                        //not support attribute type
                    }
                    break;
            }
        </td>
    </tr>
}

src/Presentation/Soft.Web/Administration/Views/Shared/_AdminLayout.cshtml
@using Soft.Core
@using Soft.Core.Domain.Customers
@using Soft.Core.Domain.Localization
@using Soft.Services.Security
@{
    var currentCustomer = WorkContext.CurrentCustomer;
    var usernamesEnabled = EngineContext.Current.Resolve<CustomerSettings>().UsernamesEnabled;
    var currentVersion = SoftVersion.CurrentVersion;
    var kendoVersion = "2014.3.1119";
    var supportRtl = EngineContext.Current.Resolve<IWorkContext>().WorkingLanguage.Rtl &&
        !EngineContext.Current.Resolve<LocalizationSettings>().IgnoreRtlPropertyForAdminArea;


    //CSS resources
    Html.AppendCssFileParts(string.Format("~/Content/kendo/{0}/kendo.rtl.min.css", kendoVersion));
    Html.AppendCssFileParts(string.Format("~/Content/kendo/{0}/kendo.default.min.css", kendoVersion));
    Html.AppendCssFileParts(string.Format("~/Content/kendo/{0}/kendo.common.min.css", kendoVersion));
    Html.AppendCssFileParts("~/Content/themes/pepper-grinder/jquery-ui.pepper-grinder.min.css");

    if (supportRtl)
    {
        Html.AppendCssFileParts("~/Administration/Content/styles.rtl.css");
    }
    else
    {
        Html.AppendCssFileParts("~/Administration/Content/styles.css");
    }

    Html.AppendScriptParts(string.Format("~/Scripts/kendo/{0}/kendo.web.min.js", kendoVersion));
    Html.AppendScriptParts("~/Scripts/admin.common.js");
    Html.AppendScriptParts("~/Scripts/jquery-migrate-1.2.1.min.js");
    Html.AppendScriptParts("~/Scripts/jquery-ui.min-1.11.1.js");
    Html.AppendScriptParts("~/Scripts/jquery.validate.unobtrusive.bootstrap.js");
    Html.AppendScriptParts("~/Scripts/jquery.validate.min.js");
    Html.AppendScriptParts("~/Scripts/jquery-1.11.2.min.js");

    //page title
    string adminPageTitle = "";
    if (!String.IsNullOrWhiteSpace(ViewBag.Title))
    {
        adminPageTitle = ViewBag.Title + " / ";
    }
    adminPageTitle += T("Admin.PageTitle").Text;

    //has "Manage Maintenance" permission?
    var canManageMaintenance = EngineContext.Current.Resolve<IPermissionService>()
        .Authorize(StandardPermissionProvider.ManageMaintenance);

    //X-UA-Compatible tag
    var commonSettings = EngineContext.Current.Resolve<CommonSettings>();
    if (commonSettings.RenderXuaCompatible)
    {
        Html.AppendHeadCustomParts(string.Format("<meta http-equiv=\"X-UA-Compatible\" content=\"{0}\"/>", commonSettings.XuaCompatibleValue));
    }
}
<!DOCTYPE html>
<html @(supportRtl ? Html.Raw("dir=\"rtl\"") : null)>
<head>
    <title>@adminPageTitle</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    @Html.SoftHeadCustom()
    @Html.SoftCssFiles(Url, ResourceLocation.Head)
    @Html.SoftScripts(Url, ResourceLocation.Head)
</head>
<body @(supportRtl ? Html.Raw("class=\"k-rtl\"") : null)>
    <div id="ajaxBusy">
        <span>&nbsp;</span>
    </div>
    <div class="master-wrapper-page k-content">
        <div class="master-wrapper-content">
            @if (IsSectionDefined("header"))
            {
                @RenderSection("header")
            }
            else
            {
                <script type="text/javascript">
                        $(document).ready(function () {
                            $("#restart-application").click(function (e) {
                                showThrobber('@Html.Raw(HttpUtility.JavaScriptStringEncode(T("Admin.Header.RestartApplication.Progress").Text))');
                            });
                        });
                </script>
                <div class="header">
                    <div class="logo">
                    </div>
                    @Html.Widget("admin_header_before")
                    <div class="languageselector">
                        @Html.Action("LanguageSelector", "Common")
                    </div>
                    @Html.Widget("admin_header_middle")
                    <div class="links">
                        @Html.ActionLink(T("Admin.Header.PublicStore").Text, "Index", "Home", new { area = "" }, null)
                        @if (canManageMaintenance)
                        {
                            <span class="separator">|</span>
                            @Html.ActionLink(T("Admin.Header.ClearCache").Text, "ClearCache", "Common")
                            <span class="separator">|</span>
                            @Html.ActionLink(T("Admin.Header.RestartApplication").Text, "RestartApplication", "Common", null, new { id = "restart-application" })
                        }
                    </div>
                    <div class="login-info">
                        @if (currentCustomer != null && currentCustomer.IsRegistered())
                        {
                            @String.Format(T("Admin.Header.LoggedInAs").Text, usernamesEnabled ? currentCustomer.Username : currentCustomer.Email)
                            <text>, </text> @Html.ActionLink(T("Admin.Header.Logout").Text, "Logout", "Customer", new { area = "" }, null)
                        }
                    </div>
                    <div class="version">
                        <span>SoftCommerce @currentVersion</span>
                    </div>
                    @Html.Widget("admin_header_after")
                </div>
            }
            @if (IsSectionDefined("headermenu"))
            {
                @RenderSection("headermenu")
            }
            else
            {
                <div class="header-menu">
                    @Html.Partial("Menu")
                </div>
            }
            @if (IsSectionDefined("statusbar"))
            {
                @RenderSection("statusbar")
            }
            else
            {
                <div class="status-bar">
                    @(EngineContext.Current.Resolve<Soft.Services.Helpers.IDateTimeHelper>().ConvertToUserTime(DateTime.Now).ToString("f"))
                </div>
            }
            <div class="content">
                @Html.Partial("Notifications")
                <div class="cph">
                    @RenderBody()
                </div>
            </div>
            <div class="throbber">
                <div class="curtain">
                </div>
                <div class="curtain-content">
                    <div>
                        <h1 class="throbber-header">Wait...</h1>
                        <p>
                            <img src="@Url.Content("~/administration/content/images/throbber-synchronizing.gif")" alt="" />
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.SoftCssFiles(Url, ResourceLocation.Foot)
    @Html.SoftScripts(Url, ResourceLocation.Foot)
</body>
</html>

src/Presentation/Soft.Web/Administration/Views/Shared/_AdminPopupLayout.cshtml
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
}
@section header
{
}
@section headermenu
{
}
@section statusbar
{
}
@RenderBody()